myToken = 0eb5b1e113b23d17cacc8d563790ef9bc2778574
head = 'Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2'
###

POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
"email": "kolya@yandex.ru",
"password": "8q8w7er9t8588"
}

###

POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
"email": "vpupkin@yandex.ru",
"password": "8q8w7er9t84"
}

###

POST http://127.0.0.1:8000/api/auth/token/logout/
Content-Type: application/json
Authorization: token 802d6391ee7c0e08a4f7879cccd3d3859ad8f8b5


###

POST http://127.0.0.1:8000/api/users/4/subscribe/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2


###

DELETE http://127.0.0.1:8000/api/users/4/subscribe/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2


###

GET http://127.0.0.1:8000/api/users/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###
GET http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json
Authorization: token 0eb5b1e113b23d17cacc8d563790ef9bc2778574

###

GET http://127.0.0.1:8000/api/ingredients/2/
Content-Type: application/json
Authorization: token 0eb5b1e113b23d17cacc8d563790ef9bc2778574

###
GET http://127.0.0.1:8000/api/ingredients/?name=ай
Content-Type: application/json
Authorization: token 0eb5b1e113b23d17cacc8d563790ef9bc2778574

###

POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

{
  "ingredients": [
    {
      "id": 56,
      "amount": 2
    }
  ],
  "tags": [
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Тест",
  "text": "Испытания работы ссылки рецептов.",
  "cooking_time": 50
}
###

PATCH http://127.0.0.1:8000/api/recipes/10/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

{
  "ingredients": [
    {
      "id": 56,
      "amount": 2
    }
  ],
  "tags": [
    2
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Меняем Имя",
  "text": "Испытания работы ссылки рецептов.",
  "cooking_time": 50
}

###

DELETE  http://127.0.0.1:8000/api/recipes/9/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET  http://127.0.0.1:8000/api/recipes/5/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/recipes/?tags=dinner
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/tags/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/tags/1/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/ingredients/5/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "vpupkin@yandex.ru",
  "username": "vasya.pupkin",
  "first_name": "Вася",
  "last_name": "Пупкин",
  "password": "8q8w7er9t8"
}

###

POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
  "email": "kolya@yandex.ru",
  "username": "kolya.pupkin",
  "first_name": "Коля",
  "last_name": "Пупкин",
  "password": "8q8w7er9t8588"
}

###

POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
"email": "vpupkin@yandex.ru",
"password": "8q8w7er9t8"
}

###
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
Authorization: token 0eb5b1e113b23d17cacc8d563790ef9bc2778574

{
  "new_password": "8q8w7er9t84",
  "current_password": "8q8w7er9t8"
}

###

GET http://127.0.0.1:8000/api/users/4/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/recipes/5/favorite/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

POST http://127.0.0.1:8000/api/recipes/4/favorite/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

DELETE http://127.0.0.1:8000/api/recipes/4/favorite/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

POST http://127.0.0.1:8000/api/recipes/2/shopping_cart/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

DELETE http://127.0.0.1:8000/api/recipes/2/shopping_cart/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2

###

GET http://127.0.0.1:8000/api/recipes/download_shopping_cart/
Content-Type: application/json
Authorization: token 74f7a245d992e2b495287105c3785cd56a4d8af2