# Generated by Django 2.2.16 on 2023-03-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230325_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Введите id ингредиентов, для приготовления блюда', related_name='ingredients', through='recipes.IngredientAmount', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Введите id ассоциирующегося тега.', related_name='recipes', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
