# Generated by Django 2.2.16 on 2023-03-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230314_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribed',
            new_name='subscription',
        ),
    ]
